/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CandidatesFields { 
    id?: boolean;
    surname?: boolean;
    name?: boolean;
    personalIdentificationNumber?: boolean;
    birhtPlace?: boolean;
    postalCode?: boolean;
    town?: boolean;
    street?: boolean;
    buildingNumber?: boolean;
    flatNumber?: boolean;
    mobileNumber?: boolean;
    email?: boolean;
    theoryStartDate?: boolean;
    practiceStartDate?: boolean;
    placeOfTraining?: boolean;
}