/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { CoursesInclude } from './coursesInclude';
import { StudentsFields } from './studentsFields';


export interface Filter6 { 
    where?: any;
    fields?: StudentsFields;
    offset?: number;
    limit?: number;
    skip?: number;
    courseId?: string;
    order?: Array<string>;
    include?: Array<CoursesInclude>;
}