/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Categories } from './categories';
import { Courses } from './courses';
import { Students } from './models';

export interface Instructors { 
    _id: string;
    nick?: string;
    email: string;
    mobileNumber: string;
    name: string;
    surname: string;
    licenceIdentifier: string;
    courses?: Array<Courses>;
    categories: Array<Categories>;
    students?: Array<Students>
}