/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LessonsFields { 
    id?: boolean;
    startDateTime?: boolean;
    d?: boolean;
    duration?: boolean;
    description?: boolean;
    instructorsId?: boolean;
    studentsId?: boolean;
}