/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { Page } from './page';
import { Students } from './students';


export interface ListPaymentsForStudentResponse { 
    data?: Array<Students>;
    page: Page;
    totalPaid?: string;
    totalDue?: string;
}