/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * (Schema options: { title: 'NewCourses', exclude: [ 'id' ] })
 */
export interface NewCourses { 
    name: string;
    startDate?: Date;
    description?: string;
    categoriesId?: string;
}