/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * (Schema options: { title: 'NewInstructorsInCourses', exclude: [ 'id' ], optional: [ 'coursesId' ] })
 */
export interface NewInstructorsInCourses { 
    nick?: string;
    email: string;
    mobileNumber: string;
    name: string;
    surname: string;
    instructorIdentifier: string;
    coursesId?: number;
}