/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * (Schema options: { title: 'NewLessonsInInstructors', exclude: [ 'id' ], optional: [ 'instructorsId' ] })
 */
export interface NewLessonsInInstructors { 
    startDateTime: Date;
    d: Date;
    duration?: number;
    description?: string;
    instructorsId?: number;
    studentsId?: number;
}