/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PaymentsFields { 
    id?: boolean;
    date?: boolean;
    amount?: boolean;
    description?: boolean;
    paidBy?: boolean;
    paidTo?: boolean;
    studentsId?: boolean;
}