/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface StudentsFields { 
    surname?: boolean;
    id?: boolean;
    name?: boolean;
    personalIdentificationNumber?: boolean;
    birthPlace?: boolean;
    postalCode?: boolean;
    town?: boolean;
    street?: boolean;
    buildingNumber?: boolean;
    flatNumber?: boolean;
    mobileNumber?: boolean;
    email?: boolean;
    courseCategory?: boolean;
    theoryStartDate?: boolean;
    practiceStartDate?: boolean;
    internalExamDate?: boolean;
    placeOfTraining?: boolean;
    archived?: boolean;
    stateRegulator?: boolean;
    instructorsId?: boolean;
    coursesId?: boolean;
}