/**
 * LoopBack Application
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Courses } from './courses';
import { Instructors } from './instructors';

export interface Students { 
    surname: string;
    _id?: string;
    name: string;
    personalIdentificationNumber?: string;
    birthPlace?: string;
    postalCode?: string;
    town?: string;
    street?: string;
    buildingNumber?: string;
    flatNumber?: string;
    mobileNumber: string;
    email: string;
    categoriesId?: string;
    theoryStartDate?: string;
    practiceStartDate?: string;
    internalExamDate?: string;
    placeOfTraining?: boolean;
    archived?: boolean;
    stateRegulator?: string;
    instructors?: Array<Instructors>;
    courses?: Array<Courses>;
    balance: string;
}