export * from './candidatesController.service';
import { CandidatesControllerService } from './candidatesController.service';
export * from './categoriesController.service';
import { CategoriesControllerService } from './categoriesController.service';
export * from './coursesCategoriesController.service';
import { CoursesCategoriesControllerService } from './coursesCategoriesController.service';
export * from './coursesController.service';
import { CoursesControllerService } from './coursesController.service';
export * from './coursesInstructorsController.service';
import { CoursesInstructorsControllerService } from './coursesInstructorsController.service';
export * from './coursesStudentsController.service';
import { CoursesStudentsControllerService } from './coursesStudentsController.service';
export * from './instructorsCategoriesController.service';
import { InstructorsCategoriesControllerService } from './instructorsCategoriesController.service';
export * from './instructorsLessonsController.service';
import { InstructorsLessonsControllerService } from './instructorsLessonsController.service';
export * from './instructorsStudentsController.service';
import { InstructorsStudentsControllerService } from './instructorsStudentsController.service';
export * from './instuctorsController.service';
import { InstuctorsControllerService } from './instuctorsController.service';
export * from './lessonsController.service';
import { LessonsControllerService } from './lessonsController.service';
export * from './paymentsController.service';
import { PaymentsControllerService } from './paymentsController.service';
export * from './pingController.service';
import { PingControllerService } from './pingController.service';
export * from './studentsController.service';
import { StudentsControllerService } from './studentsController.service';
export * from './studentsLessonsController.service';
import { StudentsLessonsControllerService } from './studentsLessonsController.service';
export * from './studentsPaymentsController.service';
import { StudentsPaymentsControllerService } from './studentsPaymentsController.service';
export const APIS = [CandidatesControllerService, CategoriesControllerService, CoursesCategoriesControllerService, CoursesControllerService, CoursesInstructorsControllerService, CoursesStudentsControllerService, InstructorsCategoriesControllerService, InstructorsLessonsControllerService, InstructorsStudentsControllerService, InstuctorsControllerService, LessonsControllerService, PaymentsControllerService, PingControllerService, StudentsControllerService, StudentsLessonsControllerService, StudentsPaymentsControllerService];
